# Welcome to Jekyll!
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Awesome Site Title
email: your-email@domain.com
description: >
  Awesome site description here
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Your Name'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

exclude: ["README.md"]