# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jean Georges
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another techie blog. Everything percieved through my five senses: music, coffee, martial arts, coding and people I care about.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000"
twitter_username: jeangougou
github_username:  jeangougou

# Build settings
markdown: kramdown


exclude: ["README.md"]